import type { Metadata } from "next";
import { Inter } from "next/font/google"
import { NuqsAdapter } from 'nuqs/adapters/next/app'

import { cn } from "@/lib/utils";
import "./globals.css";
import { QueryProviders } from "@/components/custom/query-provider";
import { Toaster } from "sonner";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(inter.className, "antialiased min-h-screen")}
      >
        <QueryProviders>
          <Toaster />
          <NuqsAdapter>
            {children}
          </NuqsAdapter>
        </QueryProviders>
      </body>
    </html>
  );
}
